version: '3'

services:
  # FILEBROWSER
  filebrowser:
    container_name: filebrowser
    image:  hurlenko/filebrowser:v2.26.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - ${FILEBROWSER_PORT}:8080
    volumes:
      - ${MEDIA_FOLDER}:/data
      - ${DOCKER_CONFIGS_PATH}/filebrowser:/config
    networks:
      - medianetwork

  # JELLYFIN
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.9.7
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT}:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${DOCKER_CONFIGS_PATH}/jellyfin:/config
      - ${SHOWS_FOLDER}:/data/tvshows
      - ${MOVIES_FOLDER}:/data/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    networks:
      - medianetwork
  
  #JACKETT
  jackett:
    image: lscr.io/linuxserver/jackett:0.21.1448
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
    volumes:
      - ${DOCKER_CONFIGS_PATH}/jackett:/config
    ports:
      - ${JACKETT_PORT}:9117
    restart: unless-stopped
    networks:
      - medianetwork

  # PHOTOPRISM
  photoprism:
    container_name: photoprism
    image:  photoprism/photoprism:231128
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - ${PHOTOPRISM_PORT}:2342
    volumes:
      - ${DOCKER_CONFIGS_PATH}/photoprism:/photoprism/storage
      - ${PICTURES_FOLDER}:/photoprism/originals
      - "./storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

    environment:
      PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password) 
      PHOTOPRISM_DISABLE_TLS: "false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
    networks:
      - medianetwork
  
  # SONARR
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${DOCKER_CONFIGS_PATH}/sonar:/config
      - ${SHOWS_FOLDER}:/tv #optional
      - ${MEDIA_FOLDER}:/downloads #optional
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    networks:
      - medianetwork
  
  # RADARR
  radarr:
    image: lscr.io/linuxserver/radarr:5.2.6
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${DOCKER_CONFIGS_PATH}/radar:/config
      - ${MOVIES_FOLDER}:/movies # optional 
      - ${MEDIA_FOLDER}:/downloads  # optional
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - medianetwork

  # QBITORRENT
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.2-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - ${DOCKER_CONFIGS_PATH}/qbittorrent:/config 
      - ${MEDIA_FOLDER}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - medianetwork
  
  # HOMER
  homer:
    image: b4bz/homer:v23.10.1
    container_name: homer
    ports:
      - ${HOMER_PORT}:8080
    volumes:
      - ./homer-config/assets/:/www/assets
    restart: unless-stopped
    networks:
      - medianetwork
    depends_on:
      - qbittorrent
      - filebrowser
      - jackett
      - radarr
      - sonarr
      - jellyfin
      - photoprism
  
  # PIHOLE
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8084:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      WEBPASSWORD: 'pihole'
    # Volumes store your data between container upgrades
    volumes:
      - '${DOCKER_CONFIGS_PATH}/pihole/etc-pihole:/etc/pihole'
      - '${DOCKER_CONFIGS_PATH}/pihole//etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      - medianetwork
      
# NETWORK DEFINITION
networks:
    medianetwork:
        name: medianetwork
        driver: bridge
