colors:
  dark:
    background: '#131313'
    card-background: '#2b2b2b'
    card-shadow: rgba(0, 0, 0, 0.4)
    highlight-hover: '#5a95f5'
    highlight-primary: '#3367d6'
    highlight-secondary: '#4285f4'
    link: '#3273dc'
    link-hover: '#ffdd57'
    text: '#eaeaea'
    text-header: '#ffffff'
    text-subtitle: '#f5f5f5'
    text-title: '#fafafa'
  light:
    background: '#f5f5f5'
    card-background: '#ffffff'
    card-shadow: rgba(0, 0, 0, 0.1)
    highlight-hover: '#5a95f5'
    highlight-primary: '#3367d6'
    highlight-secondary: '#4285f4'
    link: '#3273dc'
    link-hover: '#363636'
    text: '#363636'
    text-header: '#ffffff'
    text-subtitle: '#424242'
    text-title: '#303030'
header: false
links:
- icon: fas fa-book
  name: Wiki
  url: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md
logo: logo.png
services:
- icon: fas fa-clapperboard
  items:
  - logo: assets/tools/jellyfin.svg
    name: Jellyfin
    url: http://www.server.local:8096/web/index.html#!/home.html
  - logo: assets/tools/sonarr.png
    name: Sonarr
    url: http://www.server.local:8989/
  - logo: assets/tools/radarr.png
    name: Radarr
    url: http://www.server.local:7878/
  name: Media
- icon: fas fa-cloud
  items:
  - logo: assets/tools/qbittorrent.png
    name: qBittorrent
    url: http://www.server.local:8080
  - logo: assets/tools/jackett.png
    name: Jackett
    url: http://www.server.local:9117/
  - logo: assets/tools/pihole.png
    name: Pihole
    url: http://www.server.local:8084/admin
  name: Services
- icon: fas fa-database
  items:
  - logo: assets/tools/photoprism.jpg
    name: Photoprism
    url: http://www.server.local:2342/library/browse
  - logo: assets/tools/filebrowser.png
    name: File Browser
    url: http://www.server.local:8081/files/
  name: Storage
theme: default
