colors:
  dark:
    background: '#131313'
    card-background: '#2b2b2b'
    card-shadow: rgba(0, 0, 0, 0.4)
    highlight-hover: '#5a95f5'
    highlight-primary: '#3367d6'
    highlight-secondary: '#4285f4'
    link: '#3273dc'
    link-hover: '#ffdd57'
    text: '#eaeaea'
    text-header: '#ffffff'
    text-subtitle: '#f5f5f5'
    text-title: '#fafafa'
  light:
    background: '#f5f5f5'
    card-background: '#ffffff'
    card-shadow: rgba(0, 0, 0, 0.1)
    highlight-hover: '#5a95f5'
    highlight-primary: '#3367d6'
    highlight-secondary: '#4285f4'
    link: '#3273dc'
    link-hover: '#363636'
    text: '#363636'
    text-header: '#ffffff'
    text-subtitle: '#424242'
    text-title: '#303030'
header: false
links:
- icon: fas fa-book
  name: Wiki
  url: https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md
logo: logo.png
services:
- icon: fas fa-clapperboard
  items:
  - logo: assets/tools/jellyfin.svg
    name: Jellyfin
    url: http://192.168.0.200:8096/web/index.html#!/home.html
  - logo: assets/tools/sonarr.png
    name: Sonarr
    url: http://192.168.0.200:8989/
  - logo: assets/tools/radarr.png
    name: Radarr
    url: http://192.168.0.200:7878/
  name: Media
- icon: fas fa-cloud
  items:
  - logo: assets/tools/qbittorrent.png
    name: qBittorrent
    url: http://192.168.0.200:8080
  - logo: assets/tools/filebrowser.png
    name: File Browser
    url: http://192.168.0.200:8081/files/
  - logo: assets/tools/jackett.png
    name: Jackett
    url: http://192.168.0.200:9117/
  name: Services
- icon: fas fa-database
  items:
  - logo: assets/tools/photoprism.jpg
    name: Photoprism
    url: http://192.168.0.200:2342/library/browse
  name: Storage
theme: default
